version: "3.9"
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile-next
    ports:
      - "80:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - ./pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
